apiVersion: v1
kind: Pod
metadata:
  name: redis
  namespace: bartek
spec:
  containers:
    - name: redis
      ports:
        - containerPort: 6379
      image: redis
      resources:
        limits:
          memory: "700Mi"
        requests:
          memory: "400Mi"
