apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: bartek
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: Name=bartek-elb
  labels:
    app: api
spec:
  type: LoadBalancer
  ports:
    - port: 3000
      protocol: TCP
  selector:
    app: api
